// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJOVragED6d9-t_4bGu0thiVV8Bzpu48',
    appId: '1:1056216974066:android:a955ec9e305cac2c57866b',
    messagingSenderId: '1056216974066',
    projectId: 'daone-58141',
    storageBucket: 'daone-58141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTV3ciB7dS1QoBW9WRqqRXi7ivPFne1WM',
    appId: '1:1056216974066:ios:91b59a10b7beccf657866b',
    messagingSenderId: '1056216974066',
    projectId: 'daone-58141',
    storageBucket: 'daone-58141.appspot.com',
    androidClientId: '1056216974066-a9ednvuajc9ces8rvnoe2j29rk61ee12.apps.googleusercontent.com',
    iosClientId: '1056216974066-ihmedspioq3ogcep9hhtjghcfou3c6rf.apps.googleusercontent.com',
    iosBundleId: 'com.daone.app',
  );
}
